### ISSUE TITLE
New kymastats receiver

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/opentelemetry-collector-components#15]
**Description**
As part of https://github.com/kyma-project/telemetry-manager/issues/728 a receiver is needed which can collect metrics about all Kyma module states and conditions. A concrete proposal can be found here: https://github.com/kyma-project/telemetry-manager/blob/main/docs/contributor/arch/011-kymastatsmetrics.md

As a first step, create a receiver which collects the metrics for a hardcoded receiver

**Criterias**
- Have the new receiver buildable
- The receiver can be  configured with the typical auth config (see https://github.com/kyma-project/telemetry-manager/blob/main/docs/contributor/arch/011-kymastatsmetrics.md)
- Have a readme comparable to the upstream readme's, summarizing the API and usage pattern
- The receiver will always emit the metrics for the hardcoded telemetry module (assumption is that it is present always)
- Have unit tests assuring that emitted metrics are reflecting current module status

**Reasons**

**Attachments**

**Comment by hisarbalik** [comment]
Receiver `kymastats` emit two metrics
- `kyma.module.status.state`, emit status->state for each state value with a value `1`, contains metric attribute `state` as the value of status->state attribute
- `kyma.module.status.conditions`, emit status->conditions attribute when module provides it, the metric value depends on condition status attribute and has following values: "True" -> 1, "False" -> 0, and -1 for other values

The receiver by default will scrape only Kyma Telemetry module.

All the available metrics, metric attributes, and configuration parameters are documented.
