### ISSUE TITLE
Skeleton for custom OTEL receivers

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/opentelemetry-collector-components#16]
**Description**
As part of https://github.com/kyma-project/telemetry-manager/issues/728 we identified that we will require two new receivers, see https://github.com/kyma-project/telemetry-manager/issues/921 and https://github.com/kyma-project/telemetry-manager/issues/1003. The sources of the receivers need to be located somewhere and build and shipment procedures need to get established.

**Criterias**
- [X] Find a location for the sources of the new receivers and provide a simple skeleton module for each
- [x] Have a build/release job which build a otel-collector for the telemetry module incl. the new custom receivers
- [x] Have a release action in place to create Github release with corresponding final otel-collector image
- [x] The new version might be otel-collector:0.102.1-1.0.0

**Comment by k15r** [comment]
the image name will be `kyma-otel-collector`
