### ISSUE TITLE
Have unit test for receiver creation and termination 

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/opentelemetry-collector-components#24]
**Description**
We are currently missing an automated test assuring the basic e2e functionality of creating a receiver when a lease got aquired, and the related termination of it when loosing a lease.

**Criterias**
- Test functionality for receiver creation and termination based on lease changes
- A lease renewal will not re-create the receiver

**Reasons**

**Attachments**

**Comment by rakesh-garimella** [comment]
The missing unit test has been implemented
