### ISSUE TITLE
New leader-election-receiver

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/opentelemetry-collector-components#7]
**Description**
Have a first implementation of a decorating receiver, which will activate a nested receiver on if it got selected as leader in a leader election mechanism, see also https://github.com/kyma-project/telemetry-manager/blob/main/docs/contributor/arch/012-leader-receiver-creator.md
A dummy implementation can be found here: https://github.com/skhalash/leaderreceivercreator

**Criterias**
- Have the new receiver buildable
- The receiver can be  configured with the typical lease configuration (see https://github.com/kyma-project/telemetry-manager/blob/main/docs/contributor/arch/012-leader-receiver-creator.md)
- The receiver can be configured with a nested receiver configuration
- If the instance is able to acquire the lease, the nested receiver will be enabled
- If the instance is cannot renew the lease, the nested receiver will be destroyed and is not active
- Have a readme comparable to the upstream readme's, summarizing the API and usage pattern
- Understand what metrics are available already and define what should be added in a follow-up

**Reasons**

**Attachments**

**Comment by rakesh-garimella** [comment]
Following has been implemented:
- new receiver is buildable.
- leader election receiver takes the input from the defined config file
- When the leader election is won the sub-receiver starts and when it looses the sub-receiver stops
- The sub-receiver that has been added is `k8s cluster receiver`
- Readme has been updated
- unit tests have been added
