### ISSUE TITLE
Finalization OCC

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/opentelemetry-collector-components#90]
**Description**
When trying out the receivers the first time, I stumbled across these findings:

- [x]  kymastatsreceiver: exclude "kyma" and "moduleTemplate" resource
- [x] kymastatsreceiver: add module_groups to example
- [ ] singletonreceivercreator: use current namespace for lease if available
- [x] example in kymastatsreceiver uses kubeConfig for auth, please change to serviceAccount
- [x] example in kymastatsreceiver seem to use wrong metric kyma.module.status.condition or wrong syntax
  ```{"level":"error","ts":1721644957.6690311,"caller":"singletonreceivercreator@v0.0.1/receiver.go:69","msg":"Failed to start subreceiver","kind":"receiver","name":"singleton_receiver_creator","data_type":"metrics","error":"failed to start wrapped receiver kymastats: failed to load \"kymastats\" subreceiver config: 1 error(s) decoding:\n\n* 'metrics' has invalid keys: kyma.module.status.condition","stacktrace":"github.com/kyma-project/opentelemetry-collector-components/receiver/singletonreceivercreator.(*singletonReceiverCreator).Start.func1\n\tgithub.com/kyma-project/opentelemetry-collector-components/receiver/singletonreceivercreator@v0.0.1/receiver.go:69"}```
- [x] kymastatsreceiver: do not fail on missing "status" but print warning

**Comment by skhalash** [comment]
Identifying the current lease namespace in singletonreceivercreator is a not trivial task. We support 3 k8s auth types:
* `serviceAccount` - the current namespace can be identified using [the following hack](https://github.com/percona/percona-xtradb-cluster-operator/blob/d870f2fa836d2217aad82c63a9b16dbe7e5828d1/pkg/k8s/utils.go#L29)
* `kubeConfig` - read the current context from kubeconfig
* `none` - not possible
* Upstream module also contains a [`tls` auth type](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/internal/k8sconfig/config.go#L48), which we did not take over for some reason. If we did copy it over, we wouldn't be able to identify the current namespace in that case

After a discussion with @a-thaler we decided to drop this feature and instead make lease namespace a required field.

**Comment by skhalash** [comment]
Since it's still unclear if we are able to generate generic metrics applicable for all Kyma modules, it was decided to remove module discovery in favor of a static configuration, instructing `kymastatsreceiver` to only generate metrics for the Telemetry module.
